server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.59.129:9300
  jackson:
    default-property-inclusion: non_null
  cloud:
      inetutils:
        timeout-seconds: 10
  rabbitmq:
    host: 192.168.59.129
    username: xiamu
    password: xiamu
    virtual-host: /xiamu
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15