server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.59.129
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
xiamu:
  jwt:
    pubKeyPath: D:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: XM_TOKEN # cookie的名称