server:
  port: 10010
spring:
  application:
    name: xiamu-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
    search-service: /search/**  #路由到搜索微服务
    user-service: /user/**     #路由到用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/**  #购物车微服务
    order-service: /order/**  #订单微服务
  add-host-header: true
  sensitive-headers:  # 携带本身的head头信息   覆盖默认敏感头信息
xiamu:
  jwt:
    pubKeyPath:  D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName:  XM_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item